--- #YAML:1.0
name:               POE-Component-OpenSSH
version:            0.09
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Module::Build:        0.2808
    Moose:                0.86
    MooseX::POE:          0
    Net::OpenSSH:         0.36
    POE:                  1.006
    POE::Component::Generic:  0.1201
    POE::Test::Helpers:   1.07
    Term::ReadKey:        0
    Term::ReadPassword:   0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
